const dbTodosLabels = [
  'Stand in line at the post office and keep letting people skip you.',
  'Eat half a bag of plain rice cakes.',
  'Wash a cup.',
  'Stare at your wall. If there is anything on it, take it off, then keep staring.',
  'Go to Walgreens 3 hours before it opens.',
  'Keep checking your wallet to see if money ever magically appears.',
  'Brush your teeth for a really, really long time with a really, really tiny amount of toothpaste.',
  'Neatly fold all of your socks.',
  'Pretend to be a rug.',
  "Clean a floor that's already clean to see if you can make it even more clean.",
  'Take everything in your cupboard and sort it by alphabetical order.',
  "Go to the grocery store just to look. Don't buy anything.",
  'Think about grass growing. Really focus on it.',
  'Paint something with two different shades of gray and see which one dries first.',
  'Listen to white noise on YouTube.',
  "Do your taxes early so you'll have time to help other people with taxes later.",
  'Order some blank sheets of paper online, then keep staring out your window waiting for the delivery to show up.',
  "Walk around looking for what parking spaces you'd most likely park in if you had a car.",
  "Try to break your record for the longest time you've ever been kept on hold. Your call is important to them.",
  'Figure out how to slow down your internet connection. Savor the load times.',
  'Play chess against yourself. You can add your own commentary as long as you do it in your head.',
  'Get stuck in a traffic jam. When you get out of it, try to get back in.',
  'Watch the first minute of 10 different movies and see which one has the best first minute.',
  'Think of a word. No seriously do it, think of a word. Now try and sound it out backwards. Do that with a bunch of different words!',
  "Make a collage out of people's faces in old magazines.",
  'Put a T.V. show on, then mute it and try to guess what they are saying (or just sit there watching a muted show).',
  "Redecorate your room so it's exactly the same but mirrored.",
  'Type the phrase "I think there is something wrong with my messages." into an online language translator and flip the translation back and forth.',
  'Pet your cat, if you have a cat. Otherwise just sit there wishing you had a cat to pet, because that would be nice.',
  'Move a zipper on something up and down really fast so you sound like a DJ.',
  'Have a full conversation by yourself contemplating why we call this yellow crescent shaped food a "banana".',
  'Grab a cardboard box and decorate it like a car or something. Cut out a door that can open and close. Have fun and get creative!',
  'With your eyes closed, attempt to walk to your bedroom without bumping into things to see how well you know your house or apartment!',
  "Sing the most annoying song you can think of in the mirror while making weird/ugly faces. It's good for stress relief.",
  'Search up the significance of what your recent dreams have been about. For example, "Why was there cheese in my dream?"',
  'Search up other questions that you have been dying to know, but haven\'t had time to search up, like "Why is the sky blue?" or "Who thought that darts would be a safe game for drunk people to play in bars?"',
  'If you have a dog, go outside of your house for 5 seconds then walk back again to see how happy they are to see you.',
  'Try to find a new pattern of the alphabet, such as "qwaszxopklnmerdfcvbrtfyugh", then try to sing the new version.',
  'Learn how to make an origami walrus. The world could use more.',
  "Paint your toe nails the worst possible color so that when it starts wearing off it'll start looking better.",
  "Send a screenshot from a show to friend who doesn't know the show and make them describe what they think is happening.",
  'Bake one huge giant cookie in a pizza pan. That way you can eat all of it and still say you only had one cookie.',
  "Invent a new type of pizza, like cantaloupe pizza or whatever. Not that one though because it's not very good.",
  'Write a song parody. For example, you could sing "I tried to pet you, then you went crazy, oh what a bummer, now I have rabies." to the tune of Call Me Maybe.',
  'Put a sign at the front of your house that says "free sign" and see how long it will take for someone to take the sign.',
  'Type the middle auto-complete option on your phone to create a run-on sentence that makes no sense, then send it to people and see what they reply with.',
  'Look at boring videos on the internet and say to yourself, "I can do a video way better than these people." Then do it.',
  'Talk to your stuffed animals.',
  'Listen to music while dancing and singing.',
  'Play with your pet chase them around or let them chase you around.',
  "Drink a bottle a big dog the world's most spiciest hot sauce.",
  'Go around the house acting like an agent off mission impossible.',
  "Slide down the stairs on a pillow or a giant teddy (it's a great way to pass the time).",
  'Read all the books in your house.',
  'Spy on your family members until they look at you.',
  'Play with your pet chase them around or let them chase you around.',
  'Put water and a fish into a hamster ball and let it swim around your house.',
  'Bribe your cat with treats to get them to sing.',
  'Watch YouTube till 5am.',
  'Chase your dog around your house and see who gets tired faster.',
  'Play video games you dweeb.',
  'Go through your room and find something from when you were little.',
  'Waste time on YouTube.',
  'Draw faces on all of the eggs in your fridge.',
  'Go to sleep then your day will go without you knowing!',
  'Turn on music and go crazy.',
  'Put peanut butter on your dogs nose, and watch them lick it off...',
  'Label everything in your room and see how long it takes your parents to notice.',
  'Eat or sleep all day.',
  'Make things with paper.',
  'Run into a big mirror and scream " Narnia".',
  'Give your sibling their favorite chips, when it is actually beans inside.',
  'Slowly eat all the food in your house until you parents notice.',
  'Binge watch your favorite TV show/Movie series.',
  'Have a crazy dance party with balloons and stuffed animals alone!',
  'Drink some water! Too many people are dehydrated these days.',
  'Practice chugging large amounts of liquid.',
  'When somebody raises their hand, high five them.',
  'Draw a mushroom in the corner of your classroom whiteboard and then see how long it stays there.',
  'During a test, if your teacher walks by, cover up your test and glare suspiciously at them.',
  "Tell your teachers on the first day of school that you aren't allowed to talk to strangers.",
  'Read your book upside down and see if your teacher notices.',
  'Prove a teacher wrong.',
  "If the teacher asks where your homework is, tell them you lost it fighting a kid who said they weren't the best teacher in the school.",
  'If you have a sibling at your school, go up to them and say, "I know where you live..." in a really creepy voice.',
  'When you have a substitute, look at them creepily until they get nervous around you.',
  'Pass a note to a friend in school that says, "This teacher is great!" See what happens.',
  'When the teacher is out of the room, stand up and start teaching!',
  'Switch names with someone on the first day of school and see how long it takes the teacher to find out.',
  'Put nice messages on colorful sticky notes and stick them to some lockers.',
  'When taking a test in class, flip your page REALLY LOUDLY so everyone knows your ahead of them.',
  'Freak your teacher out by getting the whole class to stare at him or her while keeping a straight face and not moving or making any noise.',
  'Go to school early and write on the white board "[Your Name], YOU are the chosen one!" Then leave and enter the class normally like everyone else.',
  'Have everyone in your class stand on their desks and yell "Freedom!" Then charge out on the last day of school when the bell rings.',
  'Cover a trampoline in water and soap, then slide around on it.',
  'Have a contest to see who can stretch their mozzarella stick cheese the farthest.',
  'Go to the zoo and try to guess what all the animals are thinking about.',
  'Go to a restaurant and have everyone order in a different accent.',
  "Have a movie marathon with Disney movies or '80s movies or even '80s Disney movies.",
  'Complete a conversation without breaking eye contact. You are not allowed to look away until the conversation is done.',
  'Have a swivel chair race.',
  "Go to the playground at a park and swing on the swings, as long as you're still young enough for that to not be creepy.",
  'Go into a store and act like spies.',
  'Try on a bunch of clothes with your friends and see who can make the best outfit, silliest outfit, most colorful outfit, etc.',
  'Gather all your old stuff together and have a yard sale. Then split the profits and spend it all on ice cream or something.',
  'Give all of your friends nicknames describing their personalities.',
  "Have a video game tournament to see who's best at first person shooters, fighting games, and Tetris.",
  'Make a scavenger hunt with clues and puzzles and give it to one of your friends to solve and watch them suffer.',
  "Go to your friend's house at midnight and make pancakes with them.",
  'Fill up balloons with (hopefully non-toxic) paint and have a war.',
  'Go to a clothing store and have a contest on who can put together the ugliest outfit.',
  'Compare all your friends to animals and decide which each one is.',
  "Wear a blindfold, and do your friend's makeup.",
  'Have a pool party without a pool. Everyone can just sit in the living room with swim suits and goggles.',
  'Tie pillows around your stomach and back and have a sumo wrestling tournament.',
  'Dress as Pac-Man, get 4 friends dressed up as ghosts, and play tag in a public place.',
  'Go to a store and buy only three things and see who can creep the cashier out the most with them.',
  'With 3 other people, get some helium and start singing like the chipmunks at random places.',
  'Have a pick up line battle.',
  'Make zebra noises, whatever those are. Zebras are silly.',
  'Go to a bowling alley but do everything but bowl.',
  'Play checkers on one of those picnic blankets that looks like checkers.',
  'Hang out in an elevator, wait for people, and never get off.',
  'Tell a joke that only you understand.',
  "Give someone a hug while you're standing and the other person is sitting.",
  "Ask people questions as they're taking a mouthful of food so they're forced to stare at you as they rapidly chew and make stupid faces and hand gestures.",
  "Get a subtle haircut so people aren't sure whether or not to comment on it.",
  "Attempt to hide your yawn so you unintentionally look like you're having a miniature seizure.",
  'Be the first person to wake up at a sleepover and just...lay there.',
  'Bring up an old topic 5 minutes after a new topic started.',
  'Try to hug someone who wants to handshake, so they go for a hug, but then...you go for the handshake.',
  'Walk past someone in a long, empty hallway while continuously deciding whether or not to make eye contact.',
  'While someone is doing dishes, slowly put another dish in the sink.',
  'Keep looking for something and then realize it was right in your hand the whole time.',
  'Keep laughing after everyone else has stopped.',
  "When in somebody's path, move to the side, and then when the other person moves, go to the side you were originally on. When the other person goes there, keep on sidestepping left and right until somebody gives up.",
  "Go to a party and then just...stand there. Don't have anything in your hands. Just stand there, in the middle of the room.",
  "Say goodbye to your friends and then realize they're not leaving yet.",
  'Narrate your dog for a day.',
  'Turn on music and go crazy.',
  'Take a bubble bath and put the bubbles on your chin to make a beard.',
  'Play acoustic guitar in the park or something wholesome like that.',
  'Use Socks As Nunchucks.',
  'Go to sleep. Its what I should be doing.',
  'Figure out the true color of a mirror.',
  'Look at a ceiling fan for a few minutes.',
  'Make yourself a really good sandwich. You deserve it.',
  'Paint your pants to make them look like your legs.',
  'Steal all the forks from your kitchen. See if anyone notices.',
  'Listen to music while dancing and singing.',
  'Build a blanket fort in your bedroom and watch a movie in there.',
  'Cook chicken nuggets.',
  'Water your siblings, see if they grows.',
  'Annoy your siblings.',
  'Build a base out of pillows or cardboard.',
  'Annoying your cat by act like a cat.',
  'Lay in bed watch tv and eat food.',
  'Follow your pet around until they notice you.',
  "Take a bottle of mayo and hide it under your sibling's pillow. See what happens",
  'Throw socks at your ceiling fan.',
  'Map out places to hide if a murderer comes.',
  'Hide in your basement. Stay there until someone finds you.',
  'Write a comic book of your favorite characters.',
  'Take your dog for a walk and talk to them like they are a real person. See how many people notice.',
  'Run around your house and tried to advertise an imaginary hot dog.',
  'Act like spider man and jump from furniture to furniture.',
  'Sit upside down on your couch.',
  'Throw pancakes at the wall.',
  'Build a fort big enough to sleep and do things in and act like it is your house evesleepin it!',
  'If you have a cat, start meowing in different pitches/voices right next to it and wait for a response.',
  'Eat a banana as fast as you can.',
  'Cuddle with your pet.',
  'Move all your furniture around so you can jump on them across your house, pretending the floor is lava.',
  'Play a game where you have to get around your house without touching the ground.',
  'Play with your pet such as parrot or something else.',
  "Microwave marshmallows. they blow up big and then deflate and they're sticky and tasty.",
  'Ride down your staircase on a mattress.',
  'Get all the cousins in the house and make a fort.',
  'Draw with your eyes closed for 30 seconds, see what you create.',
  'Have a conversation with something on your wall.',
]

export default dbTodosLabels
